name: flutter_webrtc
description: Fork of flutter-webrtc -> Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
version: 0.9.12
homepage: https://github.com/tsukumijima/flutter-webrtc
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  dart_webrtc:
    git:
      url: https://github.com/Hexagon-HTC/dart-webrtc.git
      ref: main
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  webrtc_interface:
    git:
      url: https://github.com/Hexagon-HTC/webrtc-interface.git
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^2.0.0
  pedantic: ^1.11.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
