name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
version: 0.9.19
homepage: https://github.com/cloudwebrtc/flutter-webrtc
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  dart_webrtc:
    git:
      url: https://github.com/tsukumijima/dart-webrtc.git
      ref: f8da087cedd1371923f23e7e33bca7f042328bac
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  webrtc_interface:
    git:
      url: https://github.com/tsukumijima/webrtc-interface.git
      ref: b9d22dbdff9f0f7065b7796defe9cc2afb143fcd

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^2.0.0
  pedantic: ^1.11.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin
